### ISSUE TITLE
Math::Trig minimum version

### ISSUE THREAD

**Issue by eserte** [gryphonshafer/Geo-GoogleEarth-AutoTour#2]
On some of my smoker systems I observe test failures of t/basic_functionality.t, for example here: http://www.cpantesters.org/cpan/report/9b9daa3e-b5c7-11e6-b482-a44141eb2c80

Statistical analysis suggests that the failure happens if Math::Trig is too old. With Math::Trig 1.23 all tests pass.

**Comment by gryphonshafer** [comment]
Cool, thanks. Resolved with v1.05.
